### ISSUE TITLE
Update the transfers page to only show the recent transfers and not include the airdrop which skews the numbers

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdac-token-explorer#14]
![image](https://user-images.githubusercontent.com/344748/50251222-8d8a6080-03b9-11e9-9392-a2f8861b4dc9.png)

**Comment by lukestokes** [comment]
@piecesnbits I don't remember seeing this before so I was wondering on the previous tool we were using, did we just exclude that early data? Is there a way to limit this to just 5 months or something? Maybe in the future we could add date selection or a way to click and drag to zoom in.

**Comment by piecesnbits** [comment]
atm it starts showing data points just after the airdrop. but yes we can limit that and make it better in the future.
